//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaiThueXeDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int MaDoanhThu { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<double> TongDoanhThu { get; set; }
        public Nullable<int> SoXeKhongSuDung { get; set; }
        public string LoaiXeDuocThue { get; set; }
    }
}
