//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaiThueXeDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNopPhat
    {
        public int SoPhieuPhat { get; set; }
        public Nullable<System.DateTime> NgayPhat { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public string HoTenKhachHang { get; set; }
        public string SoChungMinh { get; set; }
        public string LyDoNopPhat { get; set; }
        public Nullable<double> SoTienNopPhat { get; set; }
        public Nullable<double> TongSoTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
